import lottie from 'lottie-web';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useRef } from 'react';
import styles from '../styles/Home.module.css';
const Home: NextPage = () => {
	const element = useRef<HTMLDivElement>(null);
	console.log(element);
	useEffect(() => {
		console.log(1);
		if (element.current)
			// add this
			lottie.loadAnimation({
				animationData: require('../public/unicorn-stretching.json'),
				container: element.current,
				loop: true,
				autoplay: true,
			});
	}, []); // add this, it triggers this effect everytime element changes

	return (
		<div className={styles.container}>
			<Head>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<div ref={element}></div>
				<h2 style={{ fontFamily: 'NanumPenScript-Regular', fontSize: 32 }}>
					환영합니다.
					<br /> 여러분들에게 Chu천 또 Chu천 해드리는 서비스입니다.
				</h2>
			</main>
		</div>
	);
};

export default Home;
