name: Send Slack message

on:
  push:
    branches: [master]
    paths-ignore:
      - '.gitignore'
      - '.dockerignore'
      - 'README.md'

jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send slack message
        uses: gwemin/DevOps_Code_Collection/CI-CD/GithubActions/slack@master
        with:
          args: slack
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_MESSAGE: 🎉 ChuChu-FrontEnd Push Message - ${{github.event.head_commit.message}} 🎉
